sdvsdv

diff --git a/.github/workflows/destroyTriggered.yml b/.github/workflows/destroyTriggered.yml
--- a/.github/workflows/destroyTriggered.yml
+++ b/.github/workflows/destroyTriggered.yml
@@ -30,18 +30,6 @@ jobs:
       with:
         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
 
-    # - name: Execute Script
-    #   run: |
-    #     repoURL="https://github.com/UttU28/Pipeline_Site.git"
-    
-    #     if [ -d "${{ github.workspace }}/Pipeline_Site" ]; then
-    #         echo "Deleting Existing Directory: ${{ github.workspace }}/Pipeline_Site"
-    #         rm -rf "${{ github.workspace }}/Pipeline_Site"
-    #     fi
-    
-    #     echo "Cloning Repo: $repoURL into directory: ${{ github.workspace }}"
-    #     git clone "$repoURL"
-
     - name: Log in to Azure CLI
       run: |
         az login --service-principal -u "${{ secrets.AZURE_CLIENT_ID }}" -p "${{ secrets.AZURE_CLIENT_SECRET }}" --tenant "${{ secrets.AZURE_TENANT_ID }}" && az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
@@ -49,13 +37,18 @@ jobs:
     - name: Terraform Init
       run: terraform init -input=false
 
-    - name: Terraform Destroy
+    - name: Download ZIP & Destroy
       run: |
-        az storage blob download --container-name vault --name tfplan --file tfplan --connection-string "${{ secrets.AZURE_STORAGE_ID }}"
-        if [ $? -eq 0 ]; then
-          echo "File DOewloaded, now DESTROYING."
-          terraform destroy --auto-approve -input=false tfplan
-        else
-          echo "Error: Failed to download tfplan, ABORTING DESTROY"
-        fi
+        az storage blob download --container-name vault --name .terraform.zip --file .terraform.zip --connection-string "${{ secrets.AZURE_STORAGE_ID }}"
+        unzip .terraform.zip
+        terraform destroy --auto-approve -input=false tfplan
+
+    # - name: Terraform Destroy
+    #   run: |
+    #     az storage blob download --container-name vault --name tfplan --file tfplan --connection-string "${{ secrets.AZURE_STORAGE_ID }}"
+    #     if [ $? -eq 0 ]; then
+    #       echo "State File DOewloaded."
+    #     else
+    #       echo "Error: Failed to download tfplan, ABORTING DESTROY"
+    #     fi
     
